<a href="https://colab.research.google.com/github/Aarohi1011/python-Training/blob/main/Day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  a = int(input("enter a number "))
  b = 10/a
  print(f"Answer:- wehen you Divide { 10 } with {a } you got { b}")
except ZeroDivisionError:
  print("Cant divide bt zero ")
print("Execution successfully ")

enter a number 0
Cant divide bt zero 
Execution successfully 


In [ ]:
try:
  a = input("enter a number:- ")
  c = int(a)
  b = 10/c
  print("division:- ",b)
except ValueError:
  print("you can not divide string with number")
print("successfully executed")

enter a number:- 5
division:-  2.0
successfully executed


In [ ]:
accountbal = 1000

try:

    def withdraw(balance):
        global accountbal

        if balance > accountbal:
            raise ValueError

        accountbal = accountbal - balance
        print(accountbal)

    withdraw(2000)

except ValueError:
    print("You cannot withdraw more than amount")

print("Execution successful")

You cannot withdraw more than amount
Execution successful


**Class and Objects**

In [ ]:
class vehicle:
  def car(a):
    print(a,"car is moving:-- ")
  def bike(b):
    print(b,"bike is moving---")

v1 = vehicle
v2 = vehicle

v1.car("audi")
v2.car(1)
v1.bike("KTM")
v2.bike(1)

if v1 == v2:
  print("true")
else:
  print("false")


audi car is moving:-- 
1 car is moving:-- 
KTM bike is moving---
1 bike is moving---
true


In [ ]:
class vehicle:
  def car(self):
    print("car is moving")
v1 = vehicle()
v2 = vehicle()

v1.car()
v2.car()

if v1 == v2:
  print("true")
else:
  print("false")

car is moving
car is moving
false


In [ ]:
class Student:

    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

        self.name1 = name
        self.marks1 = marks


s1 = Student("Amit", 88)

print(s1.name)
print(s1.marks)

s1 = Student("Aarohi", 90)

print(s1.name1)
print(s1.marks1)

Amit
88
Aarohi
90


In [ ]:
class Student:
  def __init__(self,name):
    self.name = name
  def greet(self):
    print(f"Hi i am {self.name}")

Student("Amit").greet()
Student("Aarohi").greet()

Hi i am Amit
Hi i am Aarohi


**Encapsulation**

In [ ]:
class BankAccount:
  def __init__(self,balance):
    self.__balance = balance


  def deposite(self,amt):
    if amt>0:
      self.__balance += amt

  def get_balance(self):
    return self.__balance

acc = BankAccount(1000)
acc.deposite(500)
print(acc.get_balance())
print(acc.get_balance())

1500
1500


**Inheritance**

In [ ]:
class Animal:
  def __init__(self,name):
    self.name = name
  def eat(self):
    print(f"{self.name} is eating ")

class Dog(Animal):
  def bark(self):
    print(f"{self.name} says Woof!!!! ")

d = Dog("Rox")

d.bark()
d.eat()

Rox says Woof!!!! 
Rox is eating 


**Polymorphism**

In [ ]:
class Animal:
  def speak(self):
    print("Animal makes a sound")

class Dog(Animal):
  def speak(self):
    print("Dog barks")

Animal().speak()
Dog().speak()

Animal makes a sound
Dog barks


In [ ]:
class circle:
  def area(self):
    return "Area = pi* r^2 "
class square:
  def area(self):
    return "Area = side * side "

for shape in [ circle() , square()]:
  print(shape.area())


Area = pi* r^2 
Area = side * side 


In [ ]:
from abc import ABC, abstractmethod
class Vehcile(ABC):
  def start(self):
      pass
class car(Vehcile):
  def start(self):
    print("cars starts with engine")
c = car()
c.start()

cars starts with engine


**Numpy**

In [ ]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
b = np.arange(0,20,2)
print("")
print(b)
c = np.zeros((2,2))
print("")
print(c)
d = np.ones((3,3))
print("")
print(d)
print("")
e = np.linspace(0,2,5)
print(e)

[1 2 3 4 5]

[ 0  2  4  6  8 10 12 14 16 18]

[[0. 0.]
 [0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[0.  0.5 1.  1.5 2. ]


In [ ]:
import numpy as np
arr = np.array([[1,2,3,6],[1,6,2,4]])

print(arr.shape)

print(arr.ndim)

print(arr.size)

print(arr.dtype)

print(arr.itemsize)


(2, 4)
2
8
int64
8


In [ ]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70])
print(arr[-1])
print(arr[0])

arr[2] = 99
print(arr)

70
10
[10 20 99 40 50 60 70]


In [ ]:
import numpy as np
arr = np.array([[91,42,19,40],
                [11,12,13,14],
                [21,72,23,69]])
print(arr[1,2])
print(arr[0])
print(arr[2,0])
print(arr[:,1])

13
[91 42 19 40]
21
[42 12 72]


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a[1:4])
print(a[1:3])
print(a[::-1])

[20 30 40]
[20 30]
[50 40 30 20 10]


In [ ]:
import numpy as np
m = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(m[0:2,1:3])

[[2 3]
 [5 6]]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(a**b)

[2 4 6 8]
[0 0 0 0]
[1. 1. 1. 1.]
[ 1  4  9 16]
[  1   4  27 256]


In [ ]:
import numpy as np
arr = np.array([1,4,9,16,25])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))





[1. 2. 3. 4. 5.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
11.0
9.0
8.648699324175862
74.8
